let today = new Date()
console.log(today.getFullYear())
console.log(today.getMonth())
console.log(today.getDate())
console.log(today.getDay())
console.log(today.getMinutes())
console.log(today.getSeconds())